### ISSUE TITLE
Is it possible to add a method where it'll provide rough memory that is being used by the cache stance?

### ISSUE THREAD

**Issue by mkgn** [bitfaster/BitFaster.Caching#112]
Not sure whether doing this will defeats the purpose of being "fast". But what if we want to show the rough memory usage of the cache may be in a dashboard. Can we have something like mycache.memoryusage() ? I know this may be a problem when caching objects as there are similar questions out there and no straight forward method of doing that except for attaching a profiler and find it out.

**Comment by bitfaster** [comment]
To accomplish this, two things would be required:

1. An event that fires when an item is added to the cache. There is already an event for item removal, so this is a gap that can be closed with little perf impact ([Fast ](https://github.com/bitfaster/BitFaster.Caching/wiki/What-are-the-'fast'-LRU-variants%3F)variants elide the event code, so everyone still has the option of no event + no perf hit).
2. Code that is able to analyze the size of an arbitrary type instance. This is relatively straightforward for classes/structs which do not contain references to other class instances. To contend with a graph of objects, the analyzer would need to be able to detect duplicates and avoid getting stuck in a loop analyzing cyclic references.

I can add an event solving part 1. This would enable you to analyze items as they are added and removed, and to maintain an estimate of total size by adding and subtracting from a counter.

Writing code to solve part 2 would look something like [this](https://www.codeproject.com/Tips/876878/Calculating-Optimistic-Memory-Footprint-of-Managed), but it won't scale well as reference count increases because resizing the hashset will be expensive. A slightly hackier way would be to [serialize to binary](https://www.codegrepper.com/code-examples/csharp/calculate+how+much+memory+an+object+take+c%23), but that means all items must be serializable. Note that if your cached items reference a common global static (and these exist within framework types), such objects should be ignored since they do not contribute to item size and shouldn't be double counted.  To handle things like this, you would need to reflect on the item type of each reference and filter by namespace.

I would like to keep this library focused on caching, and provide the hooks that make it useful/enable consumers. So, I can add the event, and that will enable you to roll your own memory estimate solution. You can use either of the above approaches to estimate item size. A generalized efficient, robust and configurable solution to 2 above is probably a dedicated NuGet package in itself.

**Comment by mkgn** [comment]
Sorry for the late reply. Yes, I think adding this feature will defeat the purpose of the library. Didn't really thought about it until you explained the reasons behind it. But having an event I think is an ok so that the consumers are aware of the penatlies of using it.
