### ISSUE TITLE
Expiration based on a Value's property?

### ISSUE THREAD

**Issue by mburbea** [bitfaster/BitFaster.Caching#182]
I am using this library to store cached results from some vendor API and I essentially set up my `valueFactory` to pull from a database if I already have the result or to go to the vendor api.

As part of the contract term, they set a max length I am allowed to cache a value. Obviously, not a concern for a value that came from the vendor's api, but a potential concern for a value I pulled from the database. Yes, I can check that the value is still within the absolute limit when it is retrieved from the db, but the current write expiry will give it the full length, not the length remaining time to live.  Is there anyway to have the Item's time to live be defined against a property of the value?

For example, google geocode results can only be used in a cache or stored for 30 days by contract.

**Comment by bitfaster** [comment]
I think it is possible but you would need to tweak the item policy to choose a different expiry based on the item. The default policy is fixed expiry for all items - it's the simplest thing that can work that has the cheapest cost.

Specifically you would need to replace [TLruLongTicksPolicy ](https://github.com/bitfaster/BitFaster.Caching/blob/main/BitFaster.Caching/Lru/TlruLongTicksPolicy.cs) with your own implementation, the existing definition of [ConcurrentTLru](https://github.com/bitfaster/BitFaster.Caching/blob/main/BitFaster.Caching/Lru/ConcurrentTLru.cs) is like this:

```cs
public sealed class ConcurrentTLru<K, V> 
: ConcurrentLruCore<K, V, LongTickCountLruItem<K, V>, TLruLongTicksPolicy<K, V>, TelemetryPolicy<K, V>>
{
}
```

You would switch to a `PerValueTLruLongTicksPolicy`, and define your own new cache class like this:

```cs
public sealed class NewConcurrentTLru<K, V> 
: ConcurrentLruCore<K, V, LongTickCountLruItem<K, V>, PerValueTLruLongTicksPolicy<K, V>, TelemetryPolicy<K, V>>
{
}
```

Where `PerValueTLruLongTicksPolicy` would be the same as `TLruLongTicksPolicy`, but with different CreateItem and Update methods:

```cs
 public readonly struct PerValueTLruLongTicksPolicy<K, V> : IItemPolicy<K, V, LongTickCountLruItem<K, V>>
 {
        // all other methods the same as TLruLongTicksPolicy

        // this is invoked as part of GetOrAdd - value here will be the result of calling the value factory delegate in GetOrAdd. 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public LongTickCountLruItem<K, V> CreateItem(K key, V value)
        {
            long timestamp = // TODO test value and choose to use database time or call Stopwatch.GetTimestamp()

            return new LongTickCountLruItem<K, V>(key, value, timestamp);
        }

        // this is invoked as part of Update, item.Value is the value passed into the Update method
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Update(LongTickCountLruItem<K, V> item)
        {
            long timestamp = // TODO test item.Value and choose to use database time or call Stopwatch.GetTimestamp()
            item.TickCount = timestamp;
        }
}
```

Obviously, this depends on you being able to tell the value is from the database just by inspecting it's properties - from your description it sounds like this is the case. I have never tested this so there could be a hidden problem, but I think it would work.

The purpose of using a struct and marking inline here is that it forces the JIT to do extra tricks - for example to elide unused code. The downside of this is that strange things can happen if you make the struct mutable. And obviously any code you inject will influence perf for creating and updating items.

It could be worth generalizing this as part of the library, so that you could give your own delegate to compute expiry via the builder instead of passing a fixed value:

```cs
Func<string, TimeSpan> getExpiry = { /* your code goes here */ };

ICache<int, strimg> lru = new ConcurrentLruBuilder<int, string>()
                .WithExpireAfterWrite(getExpiry)
                .Build();
```

Under the covers this would switch to the different policy/generic cache class and set up the delegate. I would also need to figure out if this should be based on TimeSpan (which is less error prone) or tick count (for ultimate speed), or both. I have tried to only provide the fastest possible options, but this can make things fiddly to use.

**Comment by bitfaster** [comment]
I edited the above sample code to give a complete working implementation and tried it out - at least in my simple test case this works.

It's not a good candidate for adding at this point, since the ITimePolicy interface would now have a broken TimeToLive property and the scoped and atomic implementations of the cache would send things like AtomicFactory<K, V> to the policy before the value is actually created. To fix would require breaking changes, so would defer this to v3.0.
