### ISSUE TITLE
[Feature request] Add MRU cache

### ISSUE THREAD

**Issue by bill-poole** [bitfaster/BitFaster.Caching#362]
We sometimes need to cache items where the older the item in the cache, the more likely it is to be accessed. Once accessed, the item is very unlikely to be accessed again. Therefore, we wish to evict/replace most-recently-used items. It would be great if a set of MRU cache types were to be made available in this fantastic library.

**Comment by ben-manes** [comment]
The LFU cache handles this type of workload very well, as it’s an admission lfu. See the [glimpse](https://github.com/bitfaster/BitFaster.Caching/wiki/Hit-Rate#glimpse) hit rates which is an analytical loop to search/analyze text.

**Comment by bitfaster** [comment]
Great insight thanks Ben! Have you tried using `ConcurrentLfu` for your workload?

I can try inverting the discard logic in the LRU policy so it discards touched items (in other words discard approx MRU item instead of LRU), but I'm not sure how well this might work without testing, and I doubt it would outperform WTinyLFU for glimpse - Ben's analysis shows it is very close to optimal for this case.

**Comment by bitfaster** [comment]
Closing this assuming LFU is a viable option.
