### ISSUE TITLE
Clearing LFU cache doesn't actually clear it

### ISSUE THREAD

**Issue by provegard** [bitfaster/BitFaster.Caching#399]
I have a situation where clearing the cache doesn't work. I can reproduce it with the following test case:

```
    [Test]
    public async Task TestClear()
    {
        var cache = new ConcurrentLfuBuilder<string, string>()
            .WithScheduler(new BackgroundThreadScheduler())
            .WithCapacity(40)
            .WithAtomicGetOrAdd()
            .AsAsyncCache()
            .Build();

        var emptyCount = 0;
        for (var a = 0; a < 200; a++)
        {
            for (var i = 0; i < 10; i++)
            {
                var str = "a" + i;
                await getOrAdd(str);
            }

            cache.Clear();
            cache.Clear(); // attempt to trigger maintenance after previous clear operation

            emptyCount += cache.Count;
        }

        Assert.That(emptyCount, Is.EqualTo(0));

        async Task getOrAdd(string key)
        {
            await cache.GetOrAddAsync(key, Task.FromResult);
        }
    }
```

When I run this test, it fails _most of the times_, but occasionally succeeds. When it fails, `emptyCount` varies from 2 to 7.

When I debugged the real situation, I ended up in `ConcurrentLfu.Trim`. Here, I noticed that:

* `this.Count` was 3.
* `this.probationLru` had something like 26 nodes in it - but it looked like multiple nodes had the same key.
* The repeated calls to `TakeCandidatesInLruOrder` produced 3 candidates.
* `TryRemove` failed to remove the candidates.

Debugging from the test has the same pattern - `TryRemove` fails since `this.dictionary` doesn't contain the candidate, so it appears to be out of sync.

I know that there is some sort of async maintenance going on (that's why I try to force maintenance in the test with the second `Clear`), but in the application where the cache is used, the entries don't go away even after a while - the count is stuck at non-zero after clearing.

**Comment by provegard** [comment]
Update: I tested with `ForegroundScheduler`, and that makes the test green of course, which means that the test doesn't reflect the real-world situation, where `BackgroundThreadScheduler` supposedly never gets around to clean things up.

**Comment by provegard** [comment]
I would have thought that calling `Clear` multiple times would work, since it calls `Maintenance` internally, which also is what the background scheduler does.

**Comment by bitfaster** [comment]
You beat me to it - I was going to try with `ForegroundScheduler`. 

I think the reason `ForegroundScheduler` is working and `BackgroundThreadScheduler` fails (even when calling `Clear` twice) is due to a bug - the `Clear` method is immediately purging the write buffer which contains the removed items that were just added by `TryRemove` - they are removed before they have been processed in the background. Foreground scheduler works because TryRemove is fully completed before the write buffer is cleared.

What isn't clear to me is how the unit test for this can pass. I will debug this in detail.

**Comment by bitfaster** [comment]
I looked at this some more yesterday - the code is wrong and leaves orphan nodes in the window/probation/protected LRUs. These are the bogus items you observed in the probation LRU.

The unit test I have passes because it only validates via the count and whether the removed keys exist. Both count and exists are based on the internal dictionary. `Clear` internally calls `TryRemove` which immediately removes the key from the dictionary (thus test criteria is met and the unit test passes). `TryRemove` also stores a record of removal in the write buffer (so the LRUs can be cleaned up by maintenance later). But since `Clear` immediately drops the buffers before maintenance, orphans are left behind in window/probation/protected. These are not observable by the test when performing only a single iteration of clear.

In your test, it is possible background maintenance runs before `Clear` drops the write buffer (so it can pass sometimes). If maintenance doesn't run, orphans are left behind and subsequent iterations build up more orphans. Since `Clear` will attempt to Trim n cache entries, the orphans with dupe keys will be processed ahead of other valid items that appear in the list after n items are processed. For example, let's say the cache is size 3 and contains keys `[a, b, c]`, but the probation LRU ends up with orphans of key a, so contains `[a, a, a, b, c]`. Trim will take n=3 candidates from probation, then attempt to remove key `a` 3 times. The next time around, it may have cleared all the orphans and produce a valid result, so it works intermittently.

I will fix this so that the write buffer items are not dropped. I will also implement an integrity check in the tests to validate the internal data structures are in a consistent state to prevent re-introducing this bug. Last month I added some soak tests for `ConcurrentLru` (multi-threaded tests that interleave different read/write method pairs), I will also get this done for LFU and check for any other similar bugs.

**Comment by khellang** [comment]
Hey @bitfaster! 👋🏻 

I think we're bumping up against the same bug. Can you confirm this also affects `ConcurrentLru<K, V>`?

Is there a workaround? Looping through entries and calling `TryRemove`?

**Comment by khellang** [comment]
I have the following code

```csharp
using BitFaster.Caching.Lru;
using System;
using System.Threading;

public  class Program
{
    private static int _counter;

    public static void Main(string[] args)
    {
        var cache = new ConcurrentLruBuilder<Guid, CacheItem>()
            .WithCapacity(10)
            .WithMetrics()
            .Build();

        for (int i = 0; i < 20; i++)
        {
            cache.GetOrAdd(Guid.NewGuid(), key => new CacheItem(Interlocked.Increment(ref _counter)));
        }

        Console.WriteLine();
        Console.WriteLine("Clear");
        Console.WriteLine();

        cache.Clear();


        for (int i = 0; i < 10; i++)
        {
            cache.GetOrAdd(Guid.NewGuid(), key => new CacheItem(Interlocked.Increment(ref _counter)));
        }
    }

    public class CacheItem : IDisposable
    {
        public CacheItem(int instanceId)
        {
            InstanceId = instanceId;
            Console.WriteLine($"{InstanceId} created.");
        }

        public int InstanceId { get; }

        public void Dispose()
        {
            Console.WriteLine($"{InstanceId} disposed.");
        }
    }
}
```

And we're seeing some pretty jarring results:

```
1 created.
2 created.
3 created.
4 created.
5 created.
6 created.
7 created.
8 created.
9 created.
10 created.
11 created.
9 disposed.
12 created.
10 disposed.
13 created.
11 disposed.
14 created.
12 disposed.
15 created.
13 disposed.
16 created.
14 disposed.
17 created.
15 disposed.
18 created.
16 disposed.
19 created.
17 disposed.
20 created.
18 disposed.

Clear

19 disposed.
20 disposed.
1 disposed.
2 disposed.
3 disposed.
4 disposed.
5 disposed.
6 disposed.
7 disposed.
8 disposed.
21 created.
22 created.
23 created.
21 disposed.
24 created.
22 disposed.
25 created.
23 disposed.
26 created.
24 disposed.
27 created.
25 disposed.
28 created.
26 disposed.
29 created.
27 disposed.
30 created.
28 disposed.
```

The eviction policy doesn't look like LRU and after calling `Clear`, it appears as if the capacity has shrunk to 2.

Are these results expected?

**Comment by khellang** [comment]
I tried switching to `ClassicLru<K, V>` and these are the results I'd expect:

```csharp
using BitFaster.Caching.Lru;
using System;
using System.Threading;

public  class Program
{
    private static int _counter;

    public static void Main(string[] args)
    {
        var cache = new ClassicLru<Guid, CacheItem>(10);

        for (int i = 0; i < 20; i++)
        {
            cache.GetOrAdd(Guid.NewGuid(), key => new CacheItem(Interlocked.Increment(ref _counter)));
        }

        Console.WriteLine();
        Console.WriteLine("Clear");
        Console.WriteLine();

        cache.Clear();

        for (int i = 0; i < 10; i++)
        {
            cache.GetOrAdd(Guid.NewGuid(), key => new CacheItem(Interlocked.Increment(ref _counter)));
        }
    }

    public class CacheItem : IDisposable
    {
        public CacheItem(int instanceId)
        {
            InstanceId = instanceId;
            Console.WriteLine($"{InstanceId} created.");
        }

        public int InstanceId { get; }

        public void Dispose()
        {
            Console.WriteLine($"{InstanceId} disposed.");
        }
    }
}
```

```
1 created.
2 created.
3 created.
4 created.
5 created.
6 created.
7 created.
8 created.
9 created.
10 created.
11 created.
1 disposed.
12 created.
2 disposed.
13 created.
3 disposed.
14 created.
4 disposed.
15 created.
5 disposed.
16 created.
6 disposed.
17 created.
7 disposed.
18 created.
8 disposed.
19 created.
9 disposed.
20 created.
10 disposed.

Clear

20 disposed.
18 disposed.
16 disposed.
14 disposed.
13 disposed.
11 disposed.
17 disposed.
19 disposed.
12 disposed.
15 disposed.
21 created.
22 created.
23 created.
24 created.
25 created.
26 created.
27 created.
28 created.
29 created.
30 created.
```

**Comment by khellang** [comment]
Tried changing to `EqualCapacityPartition`:

```csharp
var cache = new ConcurrentLru<int, CacheItem>(10, new EqualCapacityPartition(10), EqualityComparer<int>.Default);
```

That gave the following result:

```
1 created.
2 created.
3 created.
4 created.
5 created.
6 created.
7 created.
8 created.
9 created.
10 created.
11 created.
5 disposed.
12 created.
6 disposed.
13 created.
7 disposed.
14 created.
8 disposed.
15 created.
9 disposed.
16 created.
10 disposed.
17 created.
11 disposed.
18 created.
12 disposed.
19 created.
13 disposed.
20 created.
14 disposed.

Clear

15 disposed.
16 disposed.
17 disposed.
18 disposed.
1 disposed.
19 disposed.
2 disposed.
20 disposed.
3 disposed.
4 disposed.
21 created.
22 created.
23 created.
24 created.
25 created.
26 created.
27 created.
21 disposed.
28 created.
22 disposed.
29 created.
23 disposed.
30 created.
24 disposed.
```

Looks like it's related to the partitioning somehow 🤷‍♂️

**Comment by bitfaster** [comment]
Thanks for reporting this, I'll take a look at ConcurrentLru as well. There isn't any shared code, so this is a different bug. From your repro, it looks like the internal queue counters got stuck at full, I will debug it and see what's wrong.

Regarding eviction order, ConcrrentLru is an approximate LRU which trades off exact LRU order to optimize hit rate and concurrent throughput. ClassicLru provides exact LRU order, but has lower hit rate and throughput. ConcrrentLru will look more like LRU order if you replay something like a looped Zipfian distribution where some keys repeat more than others.
