### ISSUE TITLE
[Feature request] - Keys without values

### ISSUE THREAD

**Issue by DmitryMak** [bitfaster/BitFaster.Caching#564]
Is there a way to configure cache to not store values? Basically a Set instead of a Dictionary. Best I can come up with is this:

```
var cache = new FastConcurrentLru<Guid, Object>(capacity: 128);
cache.TryGet(someId, out _);
cache.AddOrUpdate(someId, null);
```

Something like this would be really nice. Will be a simpler API surface and will probably use less memory internally:
```
var cache = new FastConcurrentLru[Set]<Guid>(capacity: 128);
cache.TryGet(someId);
cache.AddOrUpdate(someId);
```

**Comment by bitfaster** [comment]
Unfortunately, that's not possible today.

Internally, all of the caches are built on top of `ConcurrentDictionary` - so without a deep rewrite the implementation will look very much like the first example you gave.

`ConcurrentDictionary` stores a [ `Node`](https://source.dot.net/#System.Collections.Concurrent/System/Collections/Concurrent/ConcurrentDictionary.cs,2188) for each entry, consisting of the key, value, next node ref and an integer hash code. Since the hash code is an int, depending on the memory size of `TKey`, `Node` will most likely have padding on a 64 bit machine. If you store the unused value as `byte` instead of `object`, it will fit inside the padding and not consume more memory, e.g.

```cs
var cache = new FastConcurrentLru<Guid, byte>(capacity: 128);
cache.TryGet(someId, out _);
cache.AddOrUpdate(someId, default);
```

**Comment by DmitryMak** [comment]
Very helpful explanation, thank you!

I wonder if this use case can be improved by creating a wrapper. For now it will just use the fake byte value. I can't see how it will be anything other than a byte because it is the smallest possible value. Basically encapsulate the best practice, and at some point the actual implementation may change.
